### ISSUE TITLE
Unable to install plasma-chain-operator

### ISSUE THREAD

**Issue by desimira** [plasma-group/plasma-chain-operator#72]
Hi, there! I run `npm install plasma-chain -g` but execution failed with "premature close" error. Thins error usually occurs when package.json file is missing or some of the dependencies in it directs to wrong git url. I see that you are currently reconstructing the PG's repo and some dependencies are removed, e.g. plasma-utils. But here it still directs to the old one which is empty now.
```
"plasma-contracts": "git+https://github.com/plasma-group/plasma-contracts.git",
    "plasma-explorer": "git+https://github.com/plasma-group/plasma-explorer.git",
    "plasma-utils": "git+https://github.com/plasma-group/plasma-utils.git"
```
Thanks!

**Comment by kfichter** [comment]
Hi! Thanks for reporting this. Just confirmed with @karlfloersch that this is indeed the issue. I think for now we should pin those dependencies to the last available versions on `npm` and eventually move everything over to `@pigi`.

**Comment by karlfloersch** [comment]
Should be fixed in https://github.com/plasma-group/plasma-chain-operator/pull/73 -- sorry about that! :) & thanks for the report!
